name = "castdrop-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"
workers_dev = false

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "castdrop"

[route]
pattern = "castdrop.commit451.com/*"
zone_name = "commit451.com"
